import React from 'react';
import assert from 'node:assert/strict';
import test from 'node:test';
import {PassThrough} from 'node:stream';
import {render} from 'ink-testing-library';
import {RpcPeer} from '../src/protocol/peer.js';
import {RuntimeClient} from '../src/protocol/client.js';
import {decode, record, type Json} from '../src/protocol/wire.js';
import {TuiController} from '../src/state/controller.js';
import {App} from '../src/ui/App.js';
import {activityFor} from '../src/ui/activity.js';
import {until} from './helpers.js';

test('busy animation survives silent model and tool phases, then stops without adding history', async t => {
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  t.after(() => {c.client.peer.close(); c.dispose();});
  c.session.connected = true;
  c.session.update({...c.session.state, running: true});
  const event = (name: string, fields: {[key: string]: Json}) => c.session.runtime({payload: decode(record(name, fields))});
  event('TurnStarted', {user_input: 'Work'});
  const app = render(<App controller={c}/>); t.after(() => app.cleanup());
  await until(() => app.lastFrame()?.includes('Waiting for model…'));
  const frame = app.lastFrame();
  const revision = c.snapshot();
  await until(() => app.lastFrame() !== frame);
  assert.equal(c.snapshot(), revision, 'animation does not mutate controller state');
  assert.equal(c.session.cells.length, 1, 'waiting never appends placeholder records');

  event('ReasoningDelta', {text: 'Private work', display_mode: 'hidden'});
  await until(() => app.lastFrame()?.includes('Thinking…'));
  assert(!app.lastFrame()?.includes('Private work'));
  const thinking = app.lastFrame();
  await until(() => app.lastFrame() !== thinking);
  event('ToolCallStarted', {tool_call_id: 'one', tool_name: 'shell', arguments: {command: 'slow command'}});
  await until(() => app.lastFrame()?.includes('Running shell…'));
  assert(!c.session.cells.find(cell => cell.kind === 'reasoning')!.streaming);
  const tool = app.lastFrame();
  await until(() => app.lastFrame() !== tool);
  c.session.update({...c.session.state, approval_waiting: 1});
  await until(() => app.lastFrame()?.includes('Waiting for your input'));
  assert.equal(activityFor(c)?.moving, false);
  c.session.update({...c.session.state, approval_waiting: 0});
  event('ToolCallFinished', {tool_call_id: 'one', tool_name: 'shell', outcome: {status: 'succeeded', stdout: 'Done'}});
  await until(() => app.lastFrame()?.includes('Waiting for model…'));
  event('AssistantContentDelta', {text: 'All done'});
  await until(() => app.lastFrame()?.includes('Responding…'));
  const cells = [...c.session.cells];
  c.session.update({...c.session.state, running: false});
  await until(() => !app.lastFrame()?.includes('Responding…'));
  assert.equal(activityFor(c), null);
  assert(c.session.cells.every(cell => !cell.streaming));
  assert.deepEqual(c.session.cells, cells);
});
