import React from 'react';
import assert from 'node:assert/strict';
import test from 'node:test';
import {PassThrough} from 'node:stream';
import {render} from 'ink-testing-library';
import {RpcPeer} from '../src/protocol/peer.js';
import {RuntimeClient} from '../src/protocol/client.js';
import {TuiController} from '../src/state/controller.js';
import {editor, edit} from '../src/state/editor.js';
import {App} from '../src/ui/App.js';
import {inputRows, TranscriptLayout} from '../src/ui/viewport.js';
import {safe} from '../src/ui/format.js';
import {until, backend} from './helpers.js';

test('real Ink input handles F keys, Unicode paste, menus, resize and secret masking', async t => {
  const b = await backend(); t.after(() => b.close());
  const c = b.controller;
  const app = render(<App controller={c}/>); t.after(() => app.cleanup());
  await until(() => app.lastFrame()?.includes('Ready'));
  app.stdin.write('\x1bOQ');
  await until(() => app.lastFrame()?.includes('Session details'));
  app.stdin.write('\x1b'); await until(() => !c.screen);
  const transcript = [...c.session.cells];
  app.stdin.write('/model');
  await until(() => app.lastFrame()?.includes('Commands'));
  app.stdin.write('\r'); await until(() => c.screen?.kind === 'list' && Boolean(c.screen.panel));
  assert(app.lastFrame()?.includes('Model'));
  assert.deepEqual(c.session.cells, transcript, 'opening a panel must not duplicate it in the transcript');
  const screen = c.screen!;
  assert.equal(screen.kind, 'list');
  if (screen.kind === 'list') await screen.items.find(item => item.label === 'View all details')!.select();
  await until(() => c.screen?.kind === 'document');
  app.stdin.write('\x1b'); await until(() => c.screen?.kind === 'list');
  app.stdin.write('\x1b'); await until(() => !c.screen);
  assert.deepEqual(c.session.cells, transcript, 'closed panels and detail pages leave no history');
  app.stdin.write('\x1b[200~中文\n👩🏽‍💻\x1b[201~');
  await until(() => c.composer.text === '中文\n👩🏽‍💻');
  await until(() => app.lastFrame()?.includes('中文'));
  c.resize(12, 40);
  await until(() => (app.lastFrame()?.split('\n').length ?? 99) <= 11);
  assert(app.lastFrame()?.includes('中文'));
  c.resize(28, 90);
  await b.client.submit('exercise'); await until(() => c.active?.kind === 'review');
  app.stdin.write('n'); await until(() => c.active?.kind === 'confirm');
  app.stdin.write('n'); await until(() => c.active?.kind === 'choose_one');
  app.stdin.write('1'); await until(() => c.active?.kind === 'input_text');
  app.stdin.write('\x1b[200~top-secret\x1b[201~');
  await until(() => app.lastFrame()?.includes('••••'));
  assert(app.frames.every(frame => !frame.includes('top-secret')));
  assert.equal(c.composer.text, '中文\n👩🏽‍💻');
  app.stdin.write('\x1b'); await until(() => !b.client.state.running);
  app.stdin.write('\x1bOS'); await until(() => c.expanded);
  app.stdin.write('\x1b[14~'); await until(() => !c.expanded);
  app.stdin.write('\x1bOP'); await until(() => c.screen?.title === 'Keyboard help');
});

test('queued prompts and commands stay visible until the backend clears them', async t => {
  const b = await backend(); t.after(() => b.close());
  const c = b.controller;
  const app = render(<App controller={c}/>); t.after(() => app.cleanup());
  await b.client.submit('wait');
  await b.client.submit('Check the queue\nKeep all of this text');
  await b.client.submitAction('system.reset');
  await until(() => app.lastFrame()?.includes('QUEUED 2'));
  assert(app.lastFrame()?.includes('Check the queue'));
  assert(app.lastFrame()?.includes('Command 1'));
  assert(app.lastFrame()?.includes('system.reset'));
  for (let index = 0; index < 4; index++) await b.client.submit(`Additional prompt ${index}`);
  await until(() => app.lastFrame()?.includes('+2 more'));
  assert(app.lastFrame()?.includes('Command 1'), 'neither queue hides the other');
  c.showSession();
  assert(c.screen?.kind === 'document');
  if (c.screen?.kind === 'document') {
    assert(c.screen.body.includes('Keep all of this text'));
    assert(c.screen.body.includes('Additional prompt 3'));
  }
  await c.key('', {escape: true});
  c.composer = editor('draft preserved'); c.resize(12, 40);
  await until(() => (app.lastFrame()?.split('\n').length ?? 99) <= 11);
  assert(app.lastFrame()?.includes('draft preserved'));
  assert(app.lastFrame()?.includes('QUEUED'));
  await b.client.interrupt(); await b.client.interrupt();
  await until(() => !b.client.state.running);
  await until(() => !app.lastFrame()?.includes('QUEUED'));
  assert.deepEqual(c.session.state.queued_commands, []);
  assert.deepEqual(c.session.state.queued_steering, []);
  assert.equal(c.composer.text, 'draft preserved');
});

test('Unicode editing and viewport folding retain complete output without terminal escapes', () => {
  let value = editor('中文👩🏽‍💻é');
  value = edit(value, '', {backspace: true});
  assert.equal(value.text, '中文👩🏽‍💻');
  value = edit(value, '', {leftArrow: true});
  value = edit(value, '', {delete: true});
  assert.equal(value.text, '中文');
  assert(!inputRows(editor('secret'), 8, 2, true, true).join('').includes('secret'));
  const c = new TuiController(new RuntimeClient(new RpcPeer(new PassThrough(), new PassThrough())));
  const output = Array.from({length: 100}, (_, index) => `line ${index}`).join('\n');
  c.session.add('tool', 'test', output);
  c.session.add('assistant', 'Reuleaux', '**Done**\n\x1b]52;c;clipboard\x07\x1b[2Jtext');
  const layout = new TranscriptLayout();
  const folded = layout.render(c.session.cells, 40, 1000, 0, false);
  assert(!folded.rows.join('\n').includes('line 50'));
  const expanded = layout.render(c.session.cells, 40, 1000, 0, true);
  assert(expanded.rows.join('\n').includes('line 50'));
  assert(!expanded.rows.join('\n').includes('clipboard'));
  assert(!expanded.rows.join('\n').includes('\x1b[2J'));
  assert(safe(expanded.rows.join('\n')).includes('Done'));
  const page = layout.render(c.session.cells, 40, 5, 50, true);
  assert.equal(page.rows.length, 5);
  c.client.peer.close(); c.dispose();
});
